config/routes.rb
Rails.application.routes.draw do
  resources :questions

  resources :projects

    root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

#attr_accessible :name

has_many :questions, :dependent => :destroy

  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/models/question.rb
class Question < ActiveRecord::Base

#attr_accessible :subject,:content

belongs_to :project

end

app/controllers/Pro_Doc.rb
I have a client's requirements. Can you please check the same and let me have your inputs

-- Project brief --

Create an online tool in Ruby on Rails that allows a user to upload a PDF template (see attached file - test-form.pdf) and a CSV spreadsheet (see attached file - dummy-data-final.csv) and then the site produces a zipped file containing the mail-merged values in multiple PDF files. The front end will use the Zurb Foundation 5 CSS framework.

Functionality to include the following:

* Upload PDF template with form fields
* Upload CSV or XLS file containing data columns to map to form fields
* Specify a file output naming convention using CSV data eg. {id}_file.pdf
* Zip files for delivery
* Produce download link
* Use CSS Framework - Foundation 5
* Allow a test file to be generated from the uploaded docs before final merge
* Heroku webserver (my account)
* Codebase to be managed in Github

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end
 
  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    1.times do
      @question = @project.questions.build
    end
  end

  # GET /projects/1/edit
  def edit
    #redirect_to root_path
    #project = Project.find(params[:id])
    #html  = render_to_string
    #kit   = IMGKit.new(html)
    #img   = kit.to_img(:png)
    #file  = Tempfile.new(["template_#{project.id}", 'png'], 'tmp',
    #:encoding => 'ascii-8bit')
    #file.write(img)
    #file.flush
    #project.avatar = file
    #project.save
    #file.unlink
    #@question = Question.find_by_project_id(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    #render :text=>params and return false
    respond_to do |format|
      if @project.save
        kit = IMGKit.new(render_to_string(:partial => 'form', :layout => false,:locals => {:project => @project})) #it takes html and any options for wkhtmltoimage
        kit.stylesheets << '/home/intel-ithub/Desktop/ROR/nf/app/assets/stylesheets/ImgKit.css' #its apply the give css to the converted image 
        t = kit.to_img(:png) # convert image to specific format
        #render :text =>t and return false
        #render :text=>t abd return false
        file_path = '/home/intel-ithub/Desktop/ROR/nf/app/assets/images/' + @project.id.to_s+ ".png" #storing path of converted file
        file = kit.to_file(file_path)
        format.html { redirect_to root_path, notice: 'Flyer was successfully updated.' }
        format.json { render :new, status: :ok, locatioFlyern: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json

  def update
    respond_to do |format|
      if @project.update(project_params)
        kit = IMGKit.new(render_to_string(:partial => 'form', :layout => false,:locals => {:project => @project}))
        kit.stylesheets << '/home/intel-ithub/Desktop/ROR/nf/app/assets/stylesheets/ImgKit.css'
        t = kit.to_img(:png) 
        file_path = '/home/intel-ithub/Desktop/ROR/nf/app/assets/images/' + @project.id.to_s+ ".png"
        file = kit.to_file(file_path)
        format.html { redirect_to root_path, notice: 'Flyer was successfully updated.' }
        format.json { render :show, status: :ok, locatioFlyern: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroyFlyer
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Flyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name,:description, questions_attributes: [:id,:project_id,:subject,:content,:_destroy, :avatar])
      #params.require(:project).permit(:name, questions_attributes: [:id,:project_id,:subject,:content, :_destroy])
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:id,:project_id, :subject, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nf" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body style="background-color: lightgray;">
    
    <div class="navbar navbar-fluid-top"  >
      <!-- <div class="navbar-inner" > -->
      <div class="container-fluid" style="background: #2f363b;">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" style="font-size: 33px;color: lightgrey;" href="#">Nf</a>
          
        <div class="container-fluid nav-collapse"  >
          <ul class="nav">
            <li><%= link_to "Flyeres", projects_path  %></li>
            <li><%= link_to "New Flyer", new_project_path %></li>
          </ul>
        </div>
      </div>
       <!--  </div> -->
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
<!-- 
      <footer>
        <p>&copy; Terms&Conditions</p>
      </footer> -->
    </div> <!-- /container -->
  </body>
</html>

app/views/projects/_form.html.erb
<%= tinymce_assets %>
<%= nested_form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'tinymce' %>
    </div>
  </div>

  <div id="questions">
    <%= f.fields_for :questions do |builder| %>
      <fieldset>
       <legend>Question:</legend>
        <%= render "question_fields", :ff => builder %>
      </fieldset>
    <% end %>
  </div>
  
  <div class="control-group">
    <%= f.link_to_add "Add Question",:questions, :class => 'btn btn-primary fbtns', :data => { :target => "#questions" }  %>
    <%= f.submit "#{f.object.new_record? ? 'Add' : 'Update'} Flyer", :class => 'btn btn-primary fbtns'%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),projects_path, :class => 'btn fbtns' %>
  </div> 

  <script type="text/javascript">
    $(document).ready(function() {
      $(function(){
        $("").hide();
        $(".show_field").on("click", function(){
            $(".control-group, .show_field").toggle();
        });
     });
   });
  </script>  

<% end %>
<%= tinymce %>

app/views/projects/_question_fields.html.erb
<div class="control-group">
  <%= ff.label :subject, :class => 'control-label' %>
  <div class="controls">
    <%= ff.text_field :subject, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
  <%= ff.label :content, :class => 'control-label' %>
  <div class="controls">
    <%= ff.text_area :content, :class => 'text_field',:rows=>3 %>
  </div>
</div>

<div class="control-group question-del">  
	<%= ff.link_to_remove "Remove",:class => 'btn btn-primary' %>
</div>

app/views/projects/edit.html.erb
<div class="new_edit_form">
	<%- model_class = Project -%>
	<div class="page-header">
  		<h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => "Flyer" %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/projects/index.html.erb
<div class="index">
	<%- model_class = Project -%>
	<div class="inside_index">
		<div class="page-header">
	  		<h1><%=t '.title', :default => "Flyers" %></h1>
	  		<%#= link_to t('.new', :default => t("helpers.links.new")),new_project_path,:class => 'btn btn-primary' %>
		</div>
		
		<div class="blocks-main">
		  	
		  	<% @projects.each_with_index do |project| %>      
		    	<div class="imgrow">
		    		
		    		<div class="outer_image">
		      			<div class="info-block">
		      				<h5><%= project.name.to_s.camelcase %></h5>
		      			</div>
		    			<%= link_to "#{ image_tag  project.id.to_s + '.png', :alt => 'click here' }".html_safe, edit_project_path(project),:class=>"" %>
		    		</div>
		    		

		    		<div class="title_footer">
		    			<h5><%= project.name.to_s.camelcase %></h5>
						<span><%="Updated #{time_ago_in_words(project.updated_at)} ago "%></em></span>
		    		</div>
		    	</div>
		  	<% end %>

		</div>
	</div>
</div>

app/views/projects/new.html.erb
<div class="new_edit_form">
	<%- model_class = Project -%>
	<div class="page-header">
  		<h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => "Flyer" %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/projects/show.html.erb
<%= form_for @project do |f| %>
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @project.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @project.description.html_safe %></dd>
 </dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<%end%>

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :project_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :project_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subject, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subject, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :content, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                questions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/index.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:project_id) %></th>
      <th><%= model_class.human_attribute_name(:subject) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.id, question_path(question) %></td>
        <td><%= question.project_id %></td>
        <td><%= question.subject %></td>
        <td><%= question.content %></td>
        <td><%=l question.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_question_path(question), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      question_path(question),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_question_path,
            :class => 'btn btn-primary' %>

app/views/questions/new.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/questions/show.html.erb
<%- model_class = Question -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @question.project_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:subject) %>:</strong></dt>
  <dd><%= @question.subject %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @question.content %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              questions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_question_path(@question), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              question_path(@question),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>